apiVersion: 1

datasources:
  - name: AIC-Prometheus
    type: prometheus
    access: proxy
    url: http://aic-prometheus:9090
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        filterByTraceID: true
      serviceMap:
        datasourceUid: AIC-Prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '(?:trace_id|traceID|TraceId)=(\w+)'
          name: TraceID
          url: '$${__value.raw}'