server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: command-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.aiincidentcommander: ERROR