server:
  port: 8081

spring:
  application:
    name: command-service

  datasource:
    url: jdbc:mysql://localhost:3306/incident_commander?createDatabaseIfNotExist=true
    username: ${ USERNAME  }
    password: ${ PASS }
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info