server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: command-service
              uri: http://command-service:8081
              predicates:
                - Path=/api/incidents/**

            - id: query-service-rest
              uri: http://query-service:8082
              predicates:
                - Path=/api/query/**

            - id: agent-service
              uri: http://agent-service:8083
              predicates:
                - Path=/api/agent/**

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info